### ISSUE TITLE
Run fail.

### ISSUE THREAD

**Issue by Leadrive** [bjwschaap/go-lvgl#4]
````log
The framebuffer device was opened successfully.
480x272, 32bpp
The framebuffer device was mapped to memory successfully.
INFO[1970-01-07T03:24:11Z] Starting go-lvgl                             
DEBU[1970-01-07T03:24:11Z] construct GUI                                
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1044b8]

runtime stack:
runtime.throw(0x156c79, 0x2a)
        /usr/local/go/src/runtime/panic.go:1117 +0x5c
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:718 +0x224

goroutine 1 [syscall]:
runtime.cgocall(0xbc4d8, 0x1c71ef8, 0x0)
        /usr/local/go/src/runtime/cgocall.go:154 +0x5c fp=0x1c71ee0 sp=0x1c71ec8 pc=0x12e5c
github.com/bjwschaap/go-lvgl/lvgl._Cfunc_lv_style_init(0x0)
        _cgo_gotypes.go:1297 +0x2c fp=0x1c71ef4 sp=0x1c71ee0 pc=0x8ebe0
github.com/bjwschaap/go-lvgl/lvgl.(*LVStyle).Init.func1(0x0)
        /home/develop/gowork/src/github.com/bjwschaap/go-lvgl/lvgl/style.go:160 +0x44 fp=0x1c71f08 sp=0x1c71ef4 pc=0x8f96c
github.com/bjwschaap/go-lvgl/lvgl.(*LVStyle).Init(0x0)
        /home/develop/gowork/src/github.com/bjwschaap/go-lvgl/lvgl/style.go:160 +0x1c fp=0x1c71f10 sp=0x1c71f08 pc=0x8f3d8
main.createScreen(0x1c44140)
        /home/develop/gowork/src/github.com/bjwschaap/go-lvgl/main.go:70 +0x20 fp=0x1c71f38 sp=0x1c71f10 pc=0xbb8a4
main.main()
        /home/develop/gowork/src/github.com/bjwschaap/go-lvgl/main.go:41 +0x174 fp=0x1c71fb8 sp=0x1c71f38 pc=0xbb674
runtime.main()
        /usr/local/go/src/runtime/proc.go:225 +0x26c fp=0x1c71fe4 sp=0x1c71fb8 pc=0x45894
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm.s:841 +0x4 fp=0x1c71fe4 sp=0x1c71fe4 pc=0x74b48

goroutine 7 [syscall]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:168 +0x158
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:23 +0x14
created by os/signal.Notify.func1.1
        /usr/local/go/src/os/signal/signal.go:151 +0x34
````

**Comment by Leadrive** [comment]
After I comment style.Init() and tstyle.Init().
the arm screen can display.
yeah!

**Comment by Leadrive** [comment]
After I comment style.Init() and tstyle.Init().
the arm screen can display.
yeah!
